package = "cmr_arm"
executable = "joystick_direct_control"
name = "joystick_direct_control"
dependencies = []

[fault_handling]
restart_attempts = 2
restart_delay = 10

[node]
buffer_size = 10
sensitivity_scaler = 0.5
starting_sensitivity = 0.5