# config/sim_waypoints_condensed.yaml

waypoints:
  - latitude: 38.161479
    longitude: -122.454630
    altitude: 488.0
  - latitude: 38.161569
    longitude: -122.454630
    altitude: 488.0
  - latitude: 38.161659
    longitude: -122.454859
    altitude: 488.0
  - latitude: 38.161839
    longitude: -122.454516
    altitude: 488.0
  - latitude: 38.162019
    longitude: -122.454630
    altitude: 488.0
  - latitude: 38.162199
    longitude: -122.454744
    altitude: 488.0
  # NORTH = FORWARD and WEST = LEFT from starting orientation
  # 0: starting position
  # 1st: 10m north 0m west
  # 2nd: 20m north 20m west
  # 3rd: 40m north 10m east
  # 4th: 60m north 0m west
  # 5th: 80m north 10m west


