# config/waypoints_engquad.yaml

waypoints:
  - latitude: 42.4442980
    longitude: -76.4834732
    altitude: 488.0
  - latitude: 42.44447
    longitude: -76.4835001
    altitude: 488.0
  - latitude: 42.4443402
    longitude: -76.4836538
    altitude: 488.0
  - latitude: 42.4442418
    longitude: -76.4840973
    altitude: 488.0
  - latitude: 42.4444618
    longitude: -76.4843766
    altitude: 488.0
  - latitude: 42.4442418
    longitude: -76.4840973
    altitude: 488.0
  - latitude: 42.4442980
    longitude: -76.4834732
    altitude: 488.0

# Points make triangle on grass patch in eng quad
# Last point same as first one to return to start

