# config/waypoints_engquad.yaml

waypoints:
  - latitude: 42.4443013
    longitude: -76.4832399
    altitude: 488.0
  - latitude: 42.44442
    longitude: -76.48325
    altitude: 488.0

# Points make triangle on grass patch in eng quad
# Last point same as first one to return to start

