# config/waypoints.yaml

waypoints:
  - latitude: 38.161479
    longitude: -122.454630
    altitude: 488.0
  - latitude: 38.161569
    longitude: -122.454630
    altitude: 488.0
  - latitude: 38.163281
    longitude: -122.455771
    altitude: 488.0
  - latitude: 38.170488
    longitude: -122.455201
    altitude: 488.0
  - latitude: 38.17048
    longitude: -122.451206
    altitude: 488.0
  - latitude: 38.174992
    longitude: -122.450065
    altitude: 488.0
  # NORTH = FORWARD and WEST = LEFT from starting orientation
  # 0: starting position
  # 1st: 2.33m north 6.17m west
  # 2nd: 200m north 100m west
  # 3rd: 500m north 50m west
  # 4th: 1km north 300m east
  # 5th: 1.5km north 400m east
