# config/waypoints_real.yaml

waypoints:
  - latitude: 42.443916
    longitude: -76.482784
    altitude: 488.0
  - latitude: 42.848563
    longitude: -78.743380
    altitude: 488.0

# First point is by upson hall (waypoint tolerance is 100.0m)
# Second point is by Buffalo, NY (northwest-ish)

