# config/waypoints_engquad.yaml

waypoints:
  - latitude: 42.444566
    longitude: -76.482430
    altitude: 488.0
  - latitude: 42.444428
    longitude: -76.482469
    altitude: 488.0
  - latitude: 42.444378
    longitude: -76.482441
    altitude: 488.0

# Points make triangle on grass patch in eng quad
# Last point same as first one to return to start

