# config/waypoints.yaml

waypoints:
  - latitude: 38.161479
    longitude: -122.454630
    altitude: 488.0
  - latitude: 38.161569
    longitude: -122.454630
    altitude: 488.0
  - latitude: 38.1618386
    longitude: -122.455089
    altitude: 488.0
  - latitude: 38.162198
    longitude: -122.454401
    altitude: 488.0
  - latitude: 38.162558
    longitude: -122.454630
    altitude: 488.0
  - latitude: 38.162917
    longitude: -122.454860
    altitude: 488.0
  # NORTH = FORWARD and WEST = LEFT from starting orientation
  # 0: starting position
  # 1st: 10m north 0m west
  # 2nd: 40m north 40m west
  # 3rd: 80m north 20m east
  # 4th: 120m north 0m west
  # 5th: 160m north 20m west
