# config/waypoints_engquad.yaml

waypoints:
  - latitude: 42.444296
    longitude: -76.483417
    altitude: 488.0
  - latitude: 42.444061 # left side
    longitude: -76.483483
    altitude: 488.0
    # last one same
  - latitude: 42.444296
    longitude: -76.483417
    altitude: 488.0

# Points make triangle on grass patch in eng quad
# Last point same as first one to return to start

