# constants for control ids
int32 MAIN_JOYSTICK_ID = 0
int32 SECOND_JOYSTICK_ID = 2
int32 THIRD_BUTTON_ID = 3
int32 FOURTH_BUTTON_ID = 4
int32 FIFTH_BUTTON_ID = 5
int32 SIXTH_BUTTON_ID = 6
int32 SEVENTH_BUTTON_ID = 7
int32 EIGHTH_BUTTON_ID = 8
int32 SENS_SLIDER_ID = 1

# constants for axis ids
int32 X_AXIS_ID = 0
int32 Y_AXIS_ID = 1
int32 Z_AXIS_ID = 2

int32 control_id
int32 axis_id
float64 magnitude