cmr_msgs/MotorData back_left
cmr_msgs/MotorData front_right
cmr_msgs/MotorData back_right
cmr_msgs/MotorData front_left

cmr_msgs/MotorData back_left_swerve
cmr_msgs/MotorData front_right_swerve
cmr_msgs/MotorData back_right_swerve
cmr_msgs/MotorData front_left_swerve

cmr_msgs/MotorData base
cmr_msgs/MotorData shoulder
cmr_msgs/MotorData elbow
cmr_msgs/MotorData wrist_r1
cmr_msgs/MotorData wrist_twist
cmr_msgs/MotorData wrist_r2


