package = "cmr_rovernet"
executable = "armnet_node"
name = "armnet"
dependencies = []

[fault_handling]
restart_attempts = 2
restart_delay = 10

[node]
can_port = "/dev/serial/by-id/usb-mjbots_fdcanusb_D9E9AF95-if00"
publish_hardware_joint_states = false
use_legacy_ik_command_mapping = true
