package = "cmr_rovernet"
executable = "drivesnet_node"
name = "drivesnet"
dependencies = []

[fault_handling]
restart_attempts = 2
restart_delay = 10

[node]
motor_max_speed = 5
gradual_increase_rate = 24
base_dynamic_ratio = 0.5