package = "cmr_fabric_wrappers"
executable = "subprocess_node"
name = "arm_fk"
dependencies = []

[fault_handling]
restart_attempts = 0
restart_delay = 10

[node]
command = "ros2 launch cmr_control forward_k_arm.launch.py"
started_indicator = "Configured and activated arm_controller"
expects_output = true
indicator_timeout = 20