package = "cmr_fabric_wrappers"
executable = "subprocess_node"
name = "ccb"
dependencies = []

[fault_handling]
restart_attempts = 0
restart_delay = 10

[node]
command = "ros2 run micro_ros_agent micro_ros_agent serial --dev /dev/ttyTHS2 -b 115200"
started_indicator = "running..."
expects_output = true
indicator_timeout = 10