package = "cmr_fabric_wrappers"
executable = "subprocess_node"
name = "drives"
dependencies = []

[fault_handling]
restart_attempts = 0
restart_delay = 10

[node]
command = "ros2 launch cmr_control drives.launch.py use_rviz:=False"
started_indicator = "Configured and activated drives_controller"
expects_output = true
indicator_timeout = 20