# Goal
# TODO(astrotech-q-4): `sequence_id` may actually be a site id; rename if so.
int8 sequence_id
---
# Result
bool success
string result_message
---
# Feedback
float32 progress_pct
string current_step
