package = "cmr_bs"
executable = "joystick"
name = "jscontroller"
dependencies = []

[fault_handling]
restart_attempts = 2
restart_delay = 10

[node]
device="/dev/cmr/joystick"
type = "armcontroller"
arm_max_speed = 3