package = "cmr_bs"
executable = "joystick"
name = "drivescontroller"
dependencies = []

[fault_handling]
restart_attempts = 2
restart_delay = 10

[node]
device="/dev/cmr/drives"
type = "drivescontroller"
max_speed = 2.5
