# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - main_arm_controller
    - end_effector_controller

  main_arm_controller:
    type: FollowJointTrajectory
    joints:
      - base_joint
      - shoulder_joint
      - elbow_joint
      - wrist_rotate
      - wrist_twist
      - wrist_rotate_two
    action_ns: follow_joint_trajectory
    default: true
  end_effector_controller:
    type: FollowJointTrajectory
    joints:
      - wrist_rotate_two
    action_ns: follow_joint_trajectory
    default: true