#!/usr/bin/env python3
from __future__ import annotations

import argparse
import datetime as dt
import re
import time
from pathlib import Path

try:
    import tomllib
except ImportError:  # pragma: no cover
    import tomli as tomllib

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "driving_stack.md"

FILES = {
    "remote_connect": ROOT / "src" / "cmr_controller_remote" / "cmr_controller_remote" / "connect.py",
    "remote_launch": ROOT / "src" / "cmr_controller_remote" / "launch" / "connect.launch.py",
    "remote_setup": ROOT / "src" / "cmr_controller_remote" / "setup.py",
    "drivesnet": ROOT / "src" / "cmr_rovernet" / "cmr_rovernet" / "drivesnet.py",
    "zenny_drives": ROOT / "src" / "cmr_rovernet" / "cmr_rovernet" / "zenny_drives_node.py",
    "drivesnet_toml": ROOT / "src" / "cmr_rovernet" / "config" / "drivesnet.toml",
    "rovernet_setup": ROOT / "src" / "cmr_rovernet" / "setup.py",
    "rovernet_utils": ROOT / "src" / "cmr_rovernet" / "cmr_rovernet" / "rovernet_utils.py",
    "swerve_controller": ROOT / "src" / "cmr_controls" / "cmr_controls" / "swerve_controller_node.py",
    "drives_launch": ROOT / "src" / "cmr_controls" / "launch" / "drives.launch.py",
    "gazebo_bridge": ROOT / "src" / "cmr_controls" / "cmr_controls" / "gazebo_drive_bridge.py",
    "gazebo_launch": ROOT / "src" / "cmr_controls" / "launch" / "gazebo_drives.launch.py",
    "simple_bot_launch": ROOT / "src" / "cmr_controls" / "launch" / "simple_bot_controller.launch.py",
    "keyboard_listener": ROOT / "src" / "cmr_controls" / "cmr_controls" / "keyboard_listener.py",
    "sim_autonomy": ROOT / "src" / "autonomous_navigation" / "launch" / "sim_autonomy.launch.py",
}

TOPIC_RE = re.compile(
    r"create_(subscription|publisher)\s*\(\s*[^,]+,\s*[\"']([^\"']+)[\"']",
    re.MULTILINE,
)
NODE_RE = re.compile(r"Node\(.*?package=['\"]([^'\"]+)['\"].*?executable=['\"]([^'\"]+)['\"]", re.DOTALL)
ENTRY_RE = re.compile(r"['\"]([^'\"]+)\s*=\s*([^:'\"]+\.[^:'\"]+:[^'\"]+)['\"]")
CONST_RE = re.compile(r"^([A-Z][A-Z0-9_]+)\s*=\s*(.+)$", re.MULTILINE)


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def find_topics(path: Path):
    text = read_text(path)
    result = {"subscription": [], "publisher": []}
    for kind, topic in TOPIC_RE.findall(text):
        result[kind].append(topic)
    return {k: sorted(dict.fromkeys(v)) for k, v in result.items()}


def find_nodes(path: Path):
    text = read_text(path)
    return [(pkg, exe) for pkg, exe in NODE_RE.findall(text)]


def find_entries(path: Path):
    text = read_text(path)
    return ENTRY_RE.findall(text)


def parse_toml(path: Path):
    if not path.exists():
        return {}
    return tomllib.loads(path.read_text(encoding="utf-8"))


def find_consts(path: Path, wanted: list[str]):
    text = read_text(path)
    found = {name: value.strip() for name, value in CONST_RE.findall(text) if name in wanted}
    return found


def rel(path: Path) -> str:
    return str(path.relative_to(ROOT))


def bullets(items: list[str]) -> str:
    if not items:
        return "- None found\n"
    return "".join(f"- `{item}`\n" for item in items)


def pairs(items: list[tuple[str, str]]) -> str:
    if not items:
        return "- None found\n"
    return "".join(f"- `{a}` -> `{b}`\n" for a, b in items)


def build_markdown() -> str:
    generated = dt.datetime.now().astimezone().strftime("%Y-%m-%d %H:%M:%S %Z")

    remote_topics = find_topics(FILES["remote_connect"])
    drivesnet_topics = find_topics(FILES["drivesnet"])
    zenny_topics = find_topics(FILES["zenny_drives"])
    swerve_topics = find_topics(FILES["swerve_controller"])
    gazebo_topics = find_topics(FILES["gazebo_bridge"])
    keyboard_topics = find_topics(FILES["keyboard_listener"])

    remote_entries = find_entries(FILES["remote_setup"])
    rovernet_entries = find_entries(FILES["rovernet_setup"])
    remote_launch_nodes = find_nodes(FILES["remote_launch"])
    drives_launch_nodes = find_nodes(FILES["drives_launch"])
    gazebo_launch_nodes = find_nodes(FILES["gazebo_launch"])
    simple_launch_nodes = find_nodes(FILES["simple_bot_launch"])
    sim_autonomy_nodes = find_nodes(FILES["sim_autonomy"])

    drivesnet_cfg = parse_toml(FILES["drivesnet_toml"])
    drivesnet_node_cfg = drivesnet_cfg.get("node", {})

    swerve_consts = find_consts(
        FILES["swerve_controller"],
        ["L", "W", "WHEEL_RADIUS", "WHEEL_CIRCUMFERENCE", "SWERVE_RATIO", "DRIVE_RATIO"],
    )
    bridge_consts = find_consts(
        FILES["gazebo_bridge"],
        [],
    )

    zenny_present = FILES["zenny_drives"].exists()

    lines = []
    lines.append("# Driving Stack")
    lines.append("")
    lines.append("> This file is generated by `scripts/update_driving_doc.py`. Run it again after changing drive-related code, or use `--watch` to keep it refreshed while you work.")
    lines.append("")
    lines.append(f"Generated: `{generated}`")
    lines.append("")
    lines.append("## Current Architecture")
    lines.append("")
    lines.append("The repository currently has three overlapping drive paths:")
    lines.append("")
    lines.append("1. `cmr_controller_remote/connect.py` converts UDP controller packets into ROS topics.")
    lines.append("2. `cmr_rovernet/drivesnet.py` consumes those ROS topics and talks to real Moteus hardware.")
    lines.append("3. `cmr_controls/swerve_controller_node.py` and `cmr_controls/gazebo_drive_bridge.py` provide separate autonomy/simulation-oriented drive paths.")
    lines.append("")
    lines.append("Those paths are related, but they are not fully unified. In practice, the repo mixes legacy rover hardware control, autonomy topics, and newer Gazebo bridge code.")
    lines.append("")
    lines.append("## End-to-End Topic Flow")
    lines.append("")
    lines.append("### 1. Remote Controller Ingress")
    lines.append(f"Source: `{rel(FILES['remote_connect'])}`")
    lines.append("")
    lines.append("`connect.py` listens on UDP and republishes the decoded controller state into ROS:")
    lines.append("")
    lines.append("- Drive UDP port: `5010`")
    lines.append("- Arm UDP port: `5020`")
    lines.append("- Mini-arm UDP port: `5030`")
    lines.append("")
    lines.append("Publishers:")
    lines.append(bullets(remote_topics["publisher"]))
    lines.append("Subscriptions:")
    lines.append(bullets(remote_topics["subscription"]))
    lines.append("Implementation notes:")
    lines.append("- The first four UDP bytes are scaled from `0..255` into `-2.5..2.5`.")
    lines.append("- Drive axes are packed into a `TwistStamped` in a nonstandard layout:")
    lines.append("- `linear.x = lx`")
    lines.append("- `linear.y = ly`")
    lines.append("- `angular.x = rx`")
    lines.append("- `angular.y = ry`")
    lines.append("- Button bytes `4..11` become `ControllerReading.button_array`.")
    lines.append("")
    lines.append("### 2. Real Rover Hardware Path")
    lines.append(f"Source: `{rel(FILES['drivesnet'])}`")
    lines.append("")
    lines.append("`drivesnet.py` is the main ROS-to-Moteus bridge for real drive hardware.")
    lines.append("")
    lines.append("Subscriptions:")
    lines.append(bullets(drivesnet_topics["subscription"]))
    lines.append("Publishers:")
    lines.append(bullets(drivesnet_topics["publisher"]))
    lines.append("Behavior summary:")
    lines.append("- `/drives_controller/cmd_vel` updates the cached joystick command state.")
    lines.append("- `wheelAnglesAndSpeeds()` computes normalized swerve wheel speeds and steering angles.")
    lines.append("- The node sends drive motor commands to Moteus IDs `1..4` and steering commands to IDs `5..8`.")
    lines.append("- `/drives_controller/cmd_buttons` updates throttle and estop-style behavior through trigger/button decoding.")
    lines.append("- `/autonomy_move` provides a separate autonomy command path with direct angles and velocity.")
    lines.append("")
    if zenny_present:
        lines.append("### 2b. Unified Rover Drive Executor")
        lines.append(f"Source: `{rel(FILES['zenny_drives'])}`")
        lines.append("")
        lines.append("`zenny_drives_node.py` is the newer consolidated rover drive executor intended to replace the fragmented manual/autonomy hardware logic.")
        lines.append("")
        lines.append("Subscriptions:")
        lines.append(bullets(zenny_topics["subscription"]))
        lines.append("Publishers:")
        lines.append(bullets(zenny_topics["publisher"]))
        lines.append("Behavior summary:")
        lines.append("- Keeps the UDP ingress in `connect.py`, but moves the actual rover drive execution into one hardware-facing node.")
        lines.append("- Uses `/drives_controller/cmd_vel` plus `/drives_controller/cmd_buttons` for manual controller driving.")
        lines.append("- Uses `/cmd_vel_drives` for autonomy or any standard ROS teleop source.")
        lines.append("- Arbitrates between manual and autonomy inputs in one place before commanding Moteus.")
        lines.append("- Writes per-session JSONL logs under `logs/driving_sessions/` for ingress events, selected commands, wheel targets, and wheel feedback snapshots.")
        lines.append("")
    lines.append("Config from `drivesnet.toml`:")
    for key, value in drivesnet_node_cfg.items():
        lines.append(f"- `{key}` = `{value}`")
    lines.append("")
    lines.append("### 3. Autonomy / Swerve Controller Path")
    lines.append(f"Source: `{rel(FILES['swerve_controller'])}`")
    lines.append("")
    lines.append("`swerve_controller_node.py` is a separate Moteus-driving node focused on autonomy and `/cmd_vel_drives` style inputs.")
    lines.append("")
    lines.append("Subscriptions:")
    lines.append(bullets(swerve_topics["subscription"]))
    lines.append("Key constants:")
    for key, value in swerve_consts.items():
        lines.append(f"- `{key}` = `{value}`")
    lines.append("Behavior summary:")
    lines.append("- `/cmd_vel_drives` is treated like a conventional holonomic twist input.")
    lines.append("- `/autonomy/move/point_turn` and `/autonomy/move/ackerman` provide autonomy-oriented drive modes.")
    lines.append("- The node initializes a single `Fdcanusb()` transport and directly commands servos `1..8`.")
    lines.append("- `wheelAnglesAndSpeeds()` converts `Vx`, `Vy`, and `omega` into four drive wheel speeds and four steer motor targets.")
    lines.append("")
    lines.append("### 4. Gazebo / Simulation Path")
    lines.append(f"Source: `{rel(FILES['gazebo_bridge'])}`")
    lines.append("")
    lines.append("`gazebo_drive_bridge.py` mirrors the drive stack into Gazebo. It does not talk to Moteus hardware.")
    lines.append("")
    lines.append("Subscriptions:")
    lines.append(bullets(gazebo_topics["subscription"]))
    lines.append("Publishers:")
    lines.append(bullets(gazebo_topics["publisher"]))
    lines.append("Behavior summary:")
    lines.append("- It accepts commands from both the remote-controller topic (`/drives_controller/cmd_vel`) and the autonomy topics.")
    lines.append("- In `effort` mode it calls Gazebo services like `/apply_joint_effort`.")
    lines.append("- In `twist` mode it republishes to a planar bot topic such as `/simple_bot/cmd_vel`.")
    lines.append("- It normalizes the nonstandard `TwistStamped` layout from `connect.py` into standard `linear.x` and `angular.z` semantics.")
    lines.append("")
    lines.append("### 5. Keyboard / Test Teleop Path")
    lines.append(f"Source: `{rel(FILES['keyboard_listener'])}`")
    lines.append("")
    lines.append("The keyboard listener is a lightweight UDP-to-`Twist` teleop node used for local testing.")
    lines.append("")
    lines.append("Publishers:")
    lines.append(bullets(keyboard_topics["publisher"]))
    lines.append("Subscriptions:")
    lines.append(bullets(keyboard_topics["subscription"]))
    lines.append("")
    lines.append("## Launch Files")
    lines.append("")
    lines.append("### Installed executables")
    lines.append("From `cmr_controller_remote/setup.py`:")
    lines.append(pairs(remote_entries))
    lines.append("From `cmr_rovernet/setup.py`:")
    lines.append(pairs(rovernet_entries))
    lines.append("### Launch wiring")
    lines.append(f"- `{rel(FILES['remote_launch'])}`")
    lines.append(pairs(remote_launch_nodes))
    lines.append(f"- `{rel(FILES['drives_launch'])}`")
    lines.append(pairs(drives_launch_nodes))
    lines.append(f"- `{rel(FILES['gazebo_launch'])}`")
    lines.append(pairs(gazebo_launch_nodes))
    lines.append(f"- `{rel(FILES['simple_bot_launch'])}`")
    lines.append(pairs(simple_launch_nodes))
    lines.append(f"- `{rel(FILES['sim_autonomy'])}`")
    lines.append(pairs(sim_autonomy_nodes))
    lines.append("")
    lines.append("## Topic Contract Reference")
    lines.append("")
    lines.append("| Topic | Type | Primary producer | Primary consumer | Notes |")
    lines.append("| --- | --- | --- | --- | --- |")
    lines.append("| `/drives_controller/cmd_vel` | `geometry_msgs/TwistStamped` | `connect.py` | `drivesnet.py`, `gazebo_drive_bridge.py` | Uses a nonstandard field mapping for joystick axes. |")
    lines.append("| `/drives_controller/cmd_buttons` | `cmr_msgs/ControllerReading` | `connect.py` | `drivesnet.py` | Trigger/button bytes remain packed in `button_array`. |")
    lines.append("| `/cmd_vel_drives` | `geometry_msgs/Twist` | keyboard/local teleop/autonomy helpers | `swerve_controller_node.py`, `gazebo_drive_bridge.py` | Closest thing to a conventional rover drive topic in this repo. |")
    lines.append("| `/autonomy/move/point_turn` | `geometry_msgs/Twist` | autonomy stack | `swerve_controller_node.py`, `gazebo_drive_bridge.py` | Used for point-turn behavior. |")
    lines.append("| `/autonomy/move/ackerman` | `cmr_msgs/AutonomyDrive` | autonomy stack | `swerve_controller_node.py`, `gazebo_drive_bridge.py` | Angle + velocity autonomy command. |")
    lines.append("| `/autonomy_move` | `cmr_msgs/AutonomyDrive` | autonomy stack | `drivesnet.py` | Legacy real-rover autonomy path. |")
    lines.append("| `/simple_bot/cmd_vel` | `geometry_msgs/Twist` | `gazebo_drive_bridge.py` in twist mode | Gazebo planar move plugin | Simulation-only test path. |")
    lines.append("")
    lines.append("## Moteus IDs and Hardware Assumptions")
    lines.append("")
    lines.append("Across the current drive code, the rover assumes:")
    lines.append("- Drive motors: IDs `1, 2, 3, 4`")
    lines.append("- Steering motors: IDs `5, 6, 7, 8`")
    lines.append("- USB/CAN transport generally comes from `moteus.Fdcanusb()` or `/dev/ttyACM0` depending on the code path.")
    lines.append("")
    lines.append("## Important Mismatches To Keep In Mind")
    lines.append("")
    lines.append("- `connect.py` publishes joystick data in a nonstandard `TwistStamped` field layout. Any downstream consumer has to know that convention.")
    lines.append("- `drivesnet.py` and `swerve_controller_node.py` overlap conceptually, but they are not one shared implementation.")
    lines.append("- The hardware autonomy topic name in `drivesnet.py` is `/autonomy_move`, while the newer autonomy/sim code uses `/autonomy/move/...` topics.")
    lines.append("- The simulation bridge is newer and cleaner than the legacy rover hardware path, but it is still an adapter rather than the canonical drive controller.")
    lines.append("")
    lines.append("## Status Of `zenny_drives_node`")
    lines.append("")
    if zenny_present:
        lines.append("A `zenny_drives_node.py` file exists in the tree and is included above as the unified rover drive executor.")
    else:
        lines.append("A `zenny_drives_node.py` file is not present in the repository at generation time. If you add it later, rerun this generator and extend the `FILES` map so it is documented here.")
    lines.append("")
    lines.append("## How To Refresh This File")
    lines.append("")
    lines.append("One-shot update:")
    lines.append("")
    lines.append("```bash")
    lines.append("python3 scripts/update_driving_doc.py")
    lines.append("```")
    lines.append("")
    lines.append("Continuous watch mode:")
    lines.append("")
    lines.append("```bash")
    lines.append("python3 scripts/update_driving_doc.py --watch")
    lines.append("```")
    lines.append("")
    return "\n".join(lines) + "\n"


def write_doc() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(build_markdown(), encoding="utf-8")
    print(f"updated {OUTPUT}")


def watched_paths() -> list[Path]:
    return [path for path in FILES.values() if path.exists()]


def snapshot(paths: list[Path]) -> dict[Path, int]:
    return {path: path.stat().st_mtime_ns for path in paths}


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the driving stack markdown document")
    parser.add_argument("--watch", action="store_true", help="Continuously rewrite the doc when source files change")
    parser.add_argument("--interval", type=float, default=1.0, help="Watch polling interval in seconds")
    args = parser.parse_args()

    write_doc()
    if not args.watch:
        return 0

    paths = watched_paths()
    previous = snapshot(paths)
    print("watching for drive-stack changes...")
    try:
        while True:
            time.sleep(args.interval)
            current_paths = watched_paths()
            current = snapshot(current_paths)
            if current != previous:
                write_doc()
                previous = current
    except KeyboardInterrupt:
        print("stopped watch mode")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
