controller_manager:
  ros__parameters:
    update_rate: 10 #Hz

    joint_state_broadcaster:
      # Doc -> https://github.com/ros-controls/ros2_controllers/blob/master/joint_state_broadcaster/doc/userdoc.rst
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      # Doc -> https://github.com/ros-controls/ros2_controllers/blob/master/forward_command_controller/doc/userdoc.rst
      type: forward_command_controller/ForwardCommandController

arm_controller:
  ros__parameters:
    joints:
      - base_rotate
      - shoulder
      - elbow
      - second_rotate
      - third_tilt
      - third_rotate
      - end_effector
    interface_name: velocity
