name: Build and test
on:
  push:
  workflow_dispatch:
  schedule:
    # 4:30 AM EST every day
    - cron: "30 8 * * *"
jobs:
  test:
    runs-on: ubuntu-latest
    # Ideally, we want to keep build and tests relatively short, but if
    # tests legitimately take longer than this it can be increased
    # (although it may be in our best interest to try and optimize tests if this
    # is the case)
    # If there are some really long tests that cannot be optimized, maybe disable
    # them in this workflow and add them to a special test workflow for PRs or
    # merges into main only
    # As of the time I'm adding this, 15 is already a pretty generous upper-bound
    timeout-minutes: 15
    container:
      image: cornellmarsrover/dev:latest
      options: --user root
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get self packages
        id: get-self-packages
        uses: autowarefoundation/autoware-github-actions/get-self-packages@v1

      - name: Build
        if: ${{ steps.get-self-packages.outputs.self-packages != '' }}
        uses: autowarefoundation/autoware-github-actions/colcon-build@v1
        with:
          rosdistro: humble
          target-packages: ${{ steps.get-self-packages.outputs.self-packages }}

      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y ros-humble-ros2-control ros-humble-ros2-controllers ros-humble-xacro ros-humble-controller-manager ros-humble-robot-state-publisher ros-humble-joint-state-broadcaster ros-humble-rviz2

      - name: Unit Tests
        id: test
        if: ${{ steps.get-self-packages.outputs.self-packages != '' }}
        uses: cornellmarsrover/ros2-test-action@v2
        with:
          rosdistro: humble
          target-packages: ${{ steps.get-self-packages.outputs.self-packages }}
          pytest-args: " -k SKIP_ALL_TESTS"
          other-test-args: "--packages-skip-regex ros2_aruco"

      # Integration tests are a little flaky, so allow retries
      - name: Integration Tests
        id: integration
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 15
          retry_on: error
          command: |
            bash scripts/test_wd.sh

      - name: Code coverage
        id: ccoverage
        run: |
          sudo apt-get update && sudo apt-get install lcov -y
          bash scripts/ci_code_coverage.sh
