name: Static Analysis
on:
  pull_request:
  workflow_dispatch:
jobs:
  lint:
    runs-on: self-hosted
    container: ros:humble
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v31

      - name: Get self packages
        id: get-self-packages
        uses: autowarefoundation/autoware-github-actions/get-self-packages@v1

      - name: Build
        if: ${{ steps.get-self-packages.outputs.self-packages != '' }}
        uses: autowarefoundation/autoware-github-actions/colcon-build@v1
        with:
          rosdistro: humble
          target-packages: ${{ steps.get-self-packages.outputs.self-packages }}

      - name: Get clang tools
        id: tools
        run: |
          sudo apt update && sudo apt install clang-format clang-tidy -y

      - name: Clean compile commands
        id: clean_db
        run: |
          bash scripts/clean_build_db_wd.sh

      - name: Static analysis
        id: analyze
        run: |
          bash scripts/check_wd.sh ${{ steps.changed-files.outputs.all_changed_files }}
